Einstellungs Aktivity erstellt + Verknüpfung zur Hauptseite hergestellt
schmitzdominic/ProjektSS17 pull request #100
Opened 2017-04-02 15:40 UTC by UliVe07

2017-04-02 15:46 UTC, schmitzdominic requested changes
Sehr gut für die Anfang aber kleine Änderungen noch von Nöten.

2017-04-02 15:46 UTC, schmitzdominic commented on app/src/main/AndroidManifest.xml
> +                android:value="de.projektss17.bonpix.A_Main" />
Sehr gut ;)

2017-04-02 15:46 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +    <string name="title_activity_a__einstellungen">A_Einstellungen</string>
Den String am besten weiter oben und nicht in die Dummy Kategorie.
Zusätzlich hier bitte den wert "Einstellungen" verwenden.

2017-04-02 15:59 UTC, schmitzdominic approved these changes
Nichts mehr gefunden.
Sehr gut ;)

2017-04-02 17:39 UTC, SemperF1 commented on app/src/main/java/de/projektss17/bonpix/S.java
> -        // TODO Activity A_Einstellungen aufrufen
Hier sollte man noch das das TODO entfernen da es ja gemacht wurde.

2017-04-02 17:46 UTC, SemperF1 requested changes
Soweit alles okay nur eben das man den TODO Text noch entfernen kann.

2017-04-02 17:47 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/S.java
> -        // TODO Activity A_Einstellungen aufrufen
Das hat er ;) rot hinterlegt bedeutet das diese Zeile entfernt wurde

2017-04-02 17:49 UTC, SemperF1 commented on app/src/main/java/de/projektss17/bonpix/S.java
> -        // TODO Activity A_Einstellungen aufrufen
Ah okay. Na dann passt ja alles. Sorry.

2017-04-02 17:52 UTC, SemperF1 approved these changes
Passt alles. War mein fehler

2017-04-03 17:15 UTC, Xantey approved these changes
Super Sache.

2017-04-03 18:08 UTC, merged