Klasse A_Favoriten erstellt und  Verknüpft.
schmitzdominic/ProjektSS17 pull request #102
Opened 2017-04-02 17:32 UTC by SemperF1

Klasse A_Favoriten erstellt 
Floating Button entfernt und in der String XML A_Favoriten hinzugefügt.

2017-04-02 17:44 UTC, schmitzdominic requested changes
Gut aber eine kleine Änderung fehlt noch.

2017-04-02 17:44 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +
Der String wert stellt den angezeigten Namen dar.
Momentan steht bei dir "A_Favoriten" drinnen. Dadurch steht jetzt auch in deiner Leiste oben A_Favoriten drinnen.
Bitte den Wert hier ändern danke ;)

2017-04-02 17:53 UTC, schmitzdominic approved these changes
https://github.com/schmitzdominic/ProjektSS17/pull/102/commits/251da38bc11391e44ebff90dfd80accf88a6e858
Dankeschön 👍  Jetzt passt alles.

2017-04-03 11:28 UTC, joeymez approved these changes
Scheint okay zu sein :)

2017-04-03 17:12 UTC, Xantey approved these changes

2017-04-03 18:39 UTC, merged