i_activity_budget - A_Budget Activity erstellt und verknüpft. XML Str…
schmitzdominic/ProjektSS17 pull request #103
Opened 2017-04-02 18:54 UTC by Sippl

i_activity_budget - A_Budget Activity erstellt und verknüpft. XML String ergänzt.

2017-04-02 19:07 UTC, schmitzdominic requested changes
Ganz gut aber bitte die 2 Sachen noch ändern, danke :)

2017-04-02 19:07 UTC, schmitzdominic commented on app/src/main/res/layout/activity_a__budget.xml
> +        app:srcCompat="@android:drawable/ic_dialog_email" />
Bitte das ic_playlist_add_white_24dp icon verwenden.
`app:srcCompat="@mipmap/ic_playlist_add_white_24dp" />`

2017-04-02 19:07 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +    <string name="title_activity_a__budget">A_Budget</string>
Der String wert stellt den angezeigten Namen dar.
Momentan steht bei dir "A_Budget" drinnen. Dadurch steht jetzt auch in deiner Leiste oben A_Budget drinnen.
Bitte den Wert hier ändern danke ;)

2017-04-02 19:19 UTC, schmitzdominic approved these changes
https://github.com/schmitzdominic/ProjektSS17/pull/103/commits/1d8aab0554a9a455772bee721d2b29dfad63d74c
Sehr gut 👍  Jetzt passt alles.

2017-04-03 12:06 UTC, SshaBrn approved these changes
Passt alles. Mir ist soweit nix aufgefallen.

2017-04-03 17:14 UTC, Xantey approved these changes
Passt alles.

2017-04-03 20:28 UTC, merged