i_activity_einstellungen_version Activity erstellt + Button + S Klass…
schmitzdominic/ProjektSS17 pull request #116
Opened 2017-04-08 12:10 UTC by UliVe07

Activity erstellt + Button + S Klasse verknüpft
Außerdem in box_einstellungen_content.xml ist in Zeile 31 ein Kommentar, ohne dem es nicht funktioniert hätte

2017-04-08 12:18 UTC, SemperF1 commented on app/src/main/res/layout/box_einstellungen_content.xml
> -        app:srcCompat="@mipmap/ic_info_outline_black_24dp" />
Sollte sich Domi oder Marcus nochmal anschauen da ich nicht genau sagen kann ob das hier seine Richtigkeit hat.

2017-04-08 12:19 UTC, SemperF1 reviewed
Sollte soweit alles Passen nur eben der teil mit dem ic_info_outline_black_24dp

2017-04-09 09:38 UTC, schmitzdominic requested changes
Hab die Ressourcen hinzugeüfgt, jetzt dürfte auch das Icon klappen.
**Bitte vorher nochmal einen fetch machen.**
Bitte nochmal überarbeiten.
Danke ;)

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/AndroidManifest.xml
> +        </activity>
Bitte die Zeile 75 - 80 raus machen, sonst deklarierst du A_Version als start Activity.

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +
Bitte nur "Version"

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +    <string name="title_activity_a__version">Version</string>
Bitte eine Eigene Kategorie Pro Activity erstellen.
Bitte Namenskonvenktion beachten und ändern,
statt title_activity_a__version bitte (rechtsklick - refactor - rename) -> title_version_screen

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/layout/box_a__version.xml
> +</android.support.design.widget.CoordinatorLayout>
Bitte den Datei namen refactoren (Namenskonvenktion!) von box_a__version in "**box_version_screen**"

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/layout/content_a__version.xml
> +</android.support.constraint.ConstraintLayout>
Bitte den Datei namen refactoren (Namenskonvenktion!) von content_a__version in "**box_version_conten**t"

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/layout/box_einstellungen_content.xml
> -        app:srcCompat="@mipmap/ic_info_outline_black_24dp" />
hatte vergessen die ressource hoch zu laden. Das passt schon, ich push das gleich ;)

2017-04-09 09:38 UTC, schmitzdominic commented on app/src/main/res/layout/box_einstellungen_content.xml
> +        <!--app:srcCompat="@mipmap/ic_info_outline_black_24dp" />-->
Bitte wieder "`<!-- -->`" entfernen. Danke ;)

2017-04-09 19:45 UTC, Sippl reviewed
Domi hat eigentlich alle Punkte aufgelistet, welche noch überarbeitet werden müssen. Außerdem habe ich auch keine Funktion gefunden, welche die aktuelle App Version anzeigt (Kein Textedit etc.)? (Falls ihr die schon implementiert habt, und nur noch nicht gepushed habt, vergesst das hier)

2017-04-10 06:46 UTC, schmitzdominic commented
Siehe Commit: https://github.com/schmitzdominic/ProjektSS17/pull/116/commits/41996d598c353d02c258767d8bcd1b4e4b6a010d
Danke das ihr die Änderungen einwandfrei umgesetzt hab 👍 
Der Fabi hat recht. Wo genau kann ich jetzt die Version sehen?

2017-04-10 09:18 UTC, Sippl reviewed
changes laufen jetzt einfwandfrei. Activity lässt sich öffnen. Jedoch wie bereits geschrieben, habt ihr noch nichts in die Content zum Version anzeigen eingebaut. Im Item stand, dass dort die APP Version angezeigt werden soll. Bei Fragen oder Unklarheiten zu den Items bitte immer fragen.

2017-04-10 13:19 UTC, schmitzdominic commented
Version wird jetzt angezeigt. https://github.com/schmitzdominic/ProjektSS17/pull/116/commits/8a77356206ef9eda18e37121590197efa4dd3d6c
Danke, kann gemerged werden!

2017-04-10 13:19 UTC, schmitzdominic approved these changes

2017-04-10 13:22 UTC, Sippl approved these changes

2017-04-10 16:19 UTC, merged