I_recyclerview_implementieren
schmitzdominic/ProjektSS17 pull request #139
Opened 2017-04-18 15:09 UTC by UliVe07

Recyclerview erstellt + Testdaten eingelesen - Layout noch nicht final

2017-04-18 15:46 UTC, joeymez approved these changes
Nach wiederholtem durchschauen und vergleichen mit Marcus seinem Text, scheint euer Code funktionell gesehen zu passen. Was mir noch Augenkrebs bereitet, ist das Layout .... Vielleicht könntet ihr euch in diesem Fall bei Marcus seinem Testcode orientieren! ;)

2017-04-18 15:55 UTC, schmitzdominic requested changes
Gut das ihr euch die Arbeit gemacht habt. Ihr habt sicher auch sehr viel dabei gelernt.
Aber, 
- Bitte mehr Struktur und Genauigkeit. 
- Es wurde in keinster weise Material Design eingehalten 
- Der Code ist kaum dokumentiert.
- Der Code ist unübersichtlich da die Klassennamen keine Rückschlüsse über ihren Inhalt geben. (Für mehr Übersicht sorgen auch Pakete)

Bitte ändert euren Code noch einmal. Orientiert euch bitte mehr an i_bons_recyclerview_test. Der Marcus hat sich dort auch Arbeit gemacht und es hat deutlich mehr Struktur. Danke.

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab3Bons.java
> +        recView = (RecyclerView)rootView.findViewById(R.id.rec_list);
wie unten beschrieben bitte die id richtig benennen.

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/C_Bons_RecyclerView_Adapter.java
> +        View view = inflater.inflate(R.layout.box_recyclerview_list_item, parent, false);
Bitte auch diese id anpassen.

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/C_Bons_RecyclerView_Adapter.java
> +        private ImageView icon2;
Die zwei können auch in einer Zeile geschrieben werden: `private ImageView icon, icon2;`

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/C_Bons_RecyclerView_Adapter.java
> +        }
bitte auch hier die id´s eindeutig machen. Danke

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/C_Recyclerview_Data.java
> +public class C_Recyclerview_Data {
Wieso brauchen wir dafür eine eigene Klasse. Gibt es keinen Weg die Befüllung übersichtlich in der A_Tab3Bons zu gestalten?

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/C_Recyclerview_List_Item.java
> +public class C_Recyclerview_List_Item {
Der Name der Klasse sagt nichts aus. Bitte den Namen in etwas aussagekräftiges ändern z.B. C_BonListItem

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/res/layout/box_recyclerview_list_item.xml
> +    android:layout_height="56dp"
Wäre nicht wrap_content klüger? damit sich das item an den Inhalt anpasst?

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/res/layout/box_recyclerview_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Geht dort kein RealtiveLayout? wäre einfacher anzupassen.

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/res/layout/box_recyclerview_list_item.xml
> +    android:paddingLeft="16dp"
Für was sollen die Items von haus aus 16dp Abstand zum Rand links haben? Bitte raus damit.

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/res/layout/box_recyclerview_list_item.xml
> +    >
Fehlt dort nicht noch das paddingTop und PaddingBottom? also der Abstand nach oben und unten zu den anderen Items? Bitte dafür immer 8dp nehmen. Siehe auch in den Material Design Unterlagen die datei 2_Layout seite 27. Danke

2017-04-18 15:55 UTC, schmitzdominic commented on app/src/main/res/layout/box_recyclerview_list_item.xml
> +        />
Bitte zentriert das Icon mehr.

2017-04-18 16:13 UTC, joeymez requested changes
Scheint als wären einige Namenskonventionen und unnötig Klassen gebaut worden .. da es sich jedoch um einen vorläufige version handelt würde ich sagen ihr überarbeitet es nochmal ;)

2017-04-18 16:38 UTC, Xantey requested changes
Johanns und Domi sollten ja schon das meiste genannt haben. Also bitte die Dateien in die richtigen Ordner und alles richtig benennen. In Slack hatte ich ja schon geschrieben, dass oben beim Scrollen noch eine Box ist, welche die Sicht auf die Elemente nicht zulässt. Ich kann euch gerade auch nicht sagen, was genau das ist, aber es muss aufjedenfall weg. Zudem hätte ich gerne, dass ihr eine Klasse C_Bons implementiert. Dem Sascha hatte ich das schon erklärt. Es geht darum, dass wir später eine Zentrale Bons klasse brauchen und diese wird dann sowohl in allen Recyclerviews (das hier ist bei weitem nicht die einzige die wir bauen müssen) und DB connections etc. verwendet. Material Design muss natürlich auch noch gemacht werden, aber ich glaube das wurde auch schon gesagt. Ich review dann erneut, wenn das ausgemerzt ist. 👍 

**Bitte merken: Es gibt einen Unterschied zwischen Pushen und Merge Requests stellen. MR's bitte erst, wenn das item komplett fertig ist in euren Augen! (Dazu zählt natürlich auch Design)**

2017-04-23 17:05 UTC, schmitzdominic commented
Bitte den relevanten Pull Request erstellen. Closed!

2017-04-23 17:05 UTC, closed without merging