i_garantie_button_implementieren
schmitzdominic/ProjektSS17 pull request #170
Opened 2017-04-25 18:15 UTC by joeymez

Fertigstellung des Items I_Garantie_Implementieren: 
----------------------------------------------------------

-> Hinzufügen eines Icons zur Behandlung der Garantie
-> Hinzufügen eines neuen Icons zum Speichern
-> Änderung des Buttons *Speichern* zu einem ImageButton (Icon)
-> Anpassung der beiden neuen Icons an die Toolbar + Material Design
-> Erstellung zweier PopUps zur Behandlung des GarantieButtons
     (jeweils wenn Garantie aktiviert wird und wenn Garantie deaktiviert wird)

-> Hinzufügen von neuen Strings in der Strings-XML für die PopUpFenster

2017-04-27 17:23 UTC, Sippl requested changes
Hallo Johanns, deine Umsetzung mit dem Button und das dieser ausgegraut wird, finde ich echt gelungen. Die Anmerkungen für meinen Change Request findest du in der Code Review.

2017-04-27 17:23 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/S.java
> +        AlertDialog.Builder builder = new AlertDialog.Builder(v.getContext());
wieso übergibst du hier eine View statt wie in der popUpDialog "AppCompatActivity" und holst dir aus dieser den Context der App? Dazu machst du gerade genau das gleiche wie in der popUpDialog nur das du hier keine Negative- und Positive Buttons hinzufügst. Bitte bau das noch einheitlich damit wir hier eine Linie haben. Zusätzlich ist mir aufgefallen das die Farbe des Alerts anders ist als in der popUpDialog, kannst du diese bitte auch noch weiß machen?  danke :slightly_smiling_face:

2017-04-27 18:35 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/S.java
> +        AlertDialog.Builder builder = new AlertDialog.Builder(v.getContext());
Nunja das ist ganz einfach erklärt! Ich habe in diesem Fall eine View benutzt, da sich die Farbe des Fenster dementsprechend in dunkel grau einfärbt.... Da es sich hier um ein InfoFenster handelt, dass sich selbst schließt, wollte ich die Farbe anders haben.

-> Wenn euch die Farbe stört ändere ich sie ab  ....
-> werde es erneut commiten!
-> bitte erneut checken und gegebenfalls ok geben

2017-04-29 13:47 UTC, dontcallme requested changes
Hi Johanns, sieht soweit alles recht gut aus, ein paar Anmerkungen hab ich dir im Code noch dagelassen.

-Über die Farbe des Garantiesymbols bin ich mir noch  nicht schlüssig, kann man aber erstmal so lassen.
- Popupfenster ist soweit OK, allerdings hast du einmal INFO und einmal Hinweis verwendet --> würde es einheitlich machen

Sonst gute Arbeit, funktioniert alles :)

2017-04-29 13:47 UTC, dontcallme commented on app/src/main/res/layout/box_ocr_manuell_screen.xml
> +                    app:srcCompat="@mipmap/ic_save_button"
Wegen der einheitlichkeit, hier bitte ic_save_button_24dp verwenden / mipmap anpassen

2017-04-29 13:47 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +    private ImageButton garantieButton, saveButton;
Ist hier wirklich ein neuer Typ ImageButton notwendig oder kann nicht einfach Button mitbenutzt werden?

2017-04-30 17:52 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +    private ImageButton garantieButton, saveButton;
Hi domi! 
Ja ein ImageButton ist in diesem Fall notwendig. Ich habe es nicht implementiert um mehr Code zu produzieren, sondern vielmehr da ein BUTTON und ein IMAGE-BUTTON komplett verschiedene Dinge sind ^^

- ein Image-Button ist ein Icon auf welches man drücken kann
- ein Button ist ein Textfeld auf welches man drücken kann

2017-04-30 17:53 UTC, joeymez commented on app/src/main/res/layout/box_ocr_manuell_screen.xml
> +                    app:srcCompat="@mipmap/ic_save_button"
wenns sein muss xD

2017-04-30 20:52 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +    private ImageButton garantieButton, saveButton;
Jo da hast du recht ;), hatte das eher auf die Funktion bezogen, die ja dieselbe ist. Aber kein Problem, ist ja nur 1 Zeile^^

2017-05-01 15:58 UTC, Sippl reviewed
Soweit funktioniert bei mir alles. Sieht super aus Johanns!!! Einzig der Change Request vom Domi mit dem Icon muss noch angepasst werden (Falls du es noch nicht hast). Danach kann ich grünes Licht geben. Wir sollten uns im Hinterkopf behalten, dass in den nächsten Sprints die Funktion jedoch noch erweitert werden muss (Damit Garantie-Ende Datum via PopUp bei Garantie hinzufügen, mitgepflegt werden kann). Keine Sorge, das jetzige Item beinhaltet noch nicht diese Anforderung (wurde bei Item Erstellung vergessen...).

2017-05-01 15:58 UTC, Sippl commented on app/src/main/res/layout/box_ocr_manuell_screen.xml
> +                    app:srcCompat="@mipmap/ic_save_button"
Hi Johanns, hast du dies was Dominik gemeint hat hier angepasst? Weil bei mir auf dem Handy erscheint das Icon ic_verified_user_24dp ein klein bisschen größer als das SAVE? Falls es so gehört und du ic_save_button bereits auf 24 dp geändert hast, dann vergiss bitte meine Aussage :D. Außerdem wäre es gut, wenn du bitte den Namen der Mipmap auf ic_save_button_24dp umzubenennen. Dann ist es einheitlich :)

2017-05-02 16:30 UTC, Sippl approved these changes
Alle Änderungswünsche angepasst, funktioniert. Von meiner Seite passt es.

2017-05-02 17:24 UTC, dontcallme approved these changes
Jetzt passt alles, von mir gibts ein OK.
Sehr Gut :)

2017-05-03 16:05 UTC, merged