i_datenbank_verbessern
schmitzdominic/ProjektSS17 pull request #172
Opened 2017-05-03 17:03 UTC by schmitzdominic

Folgendes wurde behandelt.

- Tables werden beim ersten Start created
- Es wurden im DBHandler diverse Funktionen implementiert (add, remove, update, get) der (C_Laden, C_Bon und C_Artikel)
- Es wurde ein AssetHelper implementiert der die Produkt DB einbindet
- Nun ist es auch möglich in der manuelle View einen neuen Laden hinzuzufügen
- Die BonListe im Bons Tab ließt nun alle Bons aus der DB.

2017-05-06 15:40 UTC, Xantey requested changes
All in All saubere Arbeit. Über die Namenskonventionen hatten wir ja schon beim erstellen des Codes gesprochen, bitte achtet in Zukunft darauf nicht zu krass ins Denglisch abzudriften. Mal dies und mal das zu verwenden ist nicht so vorteilhaft, lieber bleiben wir einer Linie treu. 👍

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +    private void fillMask(Uri imageUri, String ladenName, String anschrift, String datum, String sonstiges, C_Artikel[] articles){
C_Artikel[] articles ... Das ist wirklich die Krönung was euer Denglisch angeht 😄

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            for(C_Artikel article : articles){
C_Artikel article - warum dann nicht artikel? Ich würde mir wünschen wir würden uns auf Englisch einigen 😄

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                this.inflateEditRow(article.getName(), ""+article.getPreis());
article.getPreis() - hier das gleiche. Die meisten Methoden haben doch englische Namen oder? 😃

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +    public ArrayList<C_Artikel> getAllArtikelFromBon(SQLiteDatabase db, C_Bon bon){
... Ihr wisst es ja sicherlich was ich meine 😄

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +    public HashMap<Integer, Integer> getAllBonArtkel(SQLiteDatabase db){
Hier fehlt ein "i"

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +    public boolean checkIfArtikelExist(SQLiteDatabase db, String artikelName, float artikelPreis){
Bitte in Zukunft auf die Namen achten...

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +        for(C_Artikel artikel : this.getAllArtikel(db)){
C_Artikel artikel - es geht also doch? 😄

2017-05-06 15:40 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Laden.java
> +public class C_Laden {
Standard Comments wären in dieser Klasse noch nice

2017-05-07 11:40 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            for(C_Artikel article : articles){
Wäre auch ein Vorschlag. Kommentare können gern auf Deutsch sein, aber der Rest ist wirklich zum Teil schlimm.

2017-05-07 12:14 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            for(C_Artikel article : articles){
Stimmt, die Vermischungen sind echt krass, wenn man alles so aufgelistet mal sieht. Dann legen wir halt die Amtsprache Englisch fest :D

2017-05-07 12:17 UTC, schmitzdominic commented
Hi @Xantey,
Erst mal vielen dank für deine wirklich ausführliche Review.
Hab mal das meiste ins englische gebracht. Die Klassennamen hab ich noch nicht geändert. Eventuell können wir das in einem anderen Sprint noch optimieren ;)
Hier der Commit https://github.com/schmitzdominic/ProjektSS17/pull/172/commits/045563418e1cc50ff1a31a2d36d8fa9a00fd1c04

2017-05-07 12:41 UTC, Xantey requested changes
Die Variable sollte noch geändert werden. Ansonsten vielen Dank für die angenommenen Änderungen, sieht sonst alles wie gewohnt super aus. 👍

2017-05-07 12:41 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Artikel.java
> +    private String name, categorie;
categories oder category - categorie gibts nicht 😄

2017-05-07 12:41 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon.java
> +    public C_Bon(String path, String shopName, String adress, String otherInformations,
Standardcomments zum erklären der Methoden wäre vielleicht noch nice in der Klasse C_Bon

2017-05-07 15:33 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon.java
> +    public C_Bon(String path, String shopName, String adress, String otherInformations,
Das sind die Konstruktoren :D Wirklich für jeden einzelnen Getter und Setter der Klasse? das ist wirklich viel xD

2017-05-07 15:42 UTC, schmitzdominic commented
@Xantey 
Alles Dokumentiert ;) https://github.com/schmitzdominic/ProjektSS17/pull/172/commits/695a3923030ce879e5b89b1fb4e0383aacb4ccbb

2017-05-07 16:39 UTC, Xantey approved these changes
Jetzt sollte alles passen, sehr nice 👍

2017-05-08 14:31 UTC, SshaBrn approved these changes
WOW, sehr gute Arbeit. Code ist sehr gut dokumentiert und selbst für mich verständlich. Mir sind soweit keine Fehler mehr aufgefallen. Marcus hat ja bereits sehr umfangreich gereviewed. Von mir also ein dickes APPROVE.

2017-05-08 14:39 UTC, merged