i_garantie_liste_implementieren
schmitzdominic/ProjektSS17 pull request #173
Opened 2017-05-03 19:51 UTC by Sippl

- Recycler View für Garantie Liste erstellt
- Klasse C_Garantie_Adapter hinzugefügt
- box_garantie_view hinzugefügt
- Datebankanbindung vorbereitet

Bitte daran denken, dass in C_Garantie_Adapter noch einiges zukünftig angepasst werden muss, sobald die Datenbankanbindung funktioniert. Vor allem der Konstruktor MyViewHolder ist momentan nur beispielsweise so eingebunden (mit Dummy Bild etc.).

2017-05-03 20:13 UTC, joeymez requested changes
Wenn ich nicht falsch liege erkenne ich beim schnellen durchschauen keinen (großen) Unterschied zum Code vom Marcus zu den Bons .... bis auf kleinere Änderung muss daher der Code korrekt sein, da Marcus sein Code fast 1:1 das selbe wiederspiegelt :)

- Was mir jedoch derzeit noch fehlt, sind die Methoden zum Deleten und Adden von Daten (C_Garantie_Adapter)
- Ich weiß das es nur Testdaten sind, dennoch könnte man die Logik bereits implementieren (würde später Zeit sparen :) ) ... konnte ich bei meiner Recyclerview für Budget auch machen 
- Wenn diese Implementiert wurden gibts auch von mir ein OK ^^

2017-05-07 16:21 UTC, joeymez reviewed
Alles klar ... unsere Änderungswünsche wurden berücksichtigt. Von meiner Seite wir das Item Freigegeben! :)

2017-05-07 16:21 UTC, joeymez approved these changes
Alles klar ... unsere Änderungswünsche wurden berücksichtigt. Von meiner Seite wir das Item Freigegeben! :)

2017-05-08 08:17 UTC, schmitzdominic approved these changes
Sieht sehr gut aus.
Funktioniert auch bei mir, sogar die Logs werden ausgegeben. Als kleinen Tipp, benutze Log.e dann siehst du das Kommentar auch weil es in Rot angezeigt wird ;)

2017-05-08 12:04 UTC, merged