i_ocr_manuell_überarbeiten
schmitzdominic/ProjektSS17 pull request #174
Opened 2017-05-04 10:02 UTC by schmitzdominic

Komplettes Layout überarbeitet

- Tastatur Bug behoben
- Es ist nun möglich über einen Button negativ / positiv Beträg einzugeben
- Es ist nun möglich über einen extra Kommabereich, Kommabeträge einzugeben

2017-05-05 14:31 UTC, UliVe07 requested changes
Bei mir ist der gleiche Fehler wie beim Sascha aber der wird ja behoben
Mir ist im Code noch etwas aufgefallen da weiß ich nur nicht was da gemacht wird

2017-05-05 14:31 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        if(preis != null && !preis.isEmpty()){
Hier verstehe ich nicht was das IF Statement aussagt, da das gleiche in der Zeile 396 auch noch vorhanden ist

2017-05-05 19:36 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        if(preis != null && !preis.isEmpty()){
Hi Uli,
Sehr gut beobachtet, glaub wir können den Code auch unten rein packen. Ich kümmer mich am Sonntag darum. danke 👍

2017-05-07 12:22 UTC, schmitzdominic commented
Hi @UliVe07 @SshaBrn 
Hab mal alles umgesetzt und die Icons hochgeladen, nun dürfte es besser sein ;)
https://github.com/schmitzdominic/ProjektSS17/pull/174/commits/79d8bd300b935d59447ad7c77c08faa267bce44a
https://github.com/schmitzdominic/ProjektSS17/pull/174/commits/aaad7684acbab2006798d22a9db904978d8424f6

2017-05-08 08:58 UTC, SshaBrn requested changes
Build funktioniert ganz gut. Design ist gut gelungen. Code ist gut dokumentiert und übersichtlich.
Eine Kleinigkeit was mir aufgefallen ist:
- der Gesamtpreis wird bei z.B. 20,30 als 20,3 ausgegeben

sollte meiner Meinung nach noch geändert werden, um nicht zu Verwirrungen bei den Usern zu führen.

Ansonsten Top ;)

2017-05-08 09:00 UTC, Sippl commented
@SshaBrn Das mit dem Komma haben wir in Kauf genommen, da es nicht die Funktion einschränkt. Aber du hast recht, usability mäßig wäre es besser beide Nachkommastellen stets anzuzeigen.

2017-05-08 09:02 UTC, schmitzdominic commented
@SshaBrn 
Danke für deine Review 👍 
Habs gleich mal geändert ;) https://github.com/schmitzdominic/ProjektSS17/pull/174/commits/a3e7e6f7495a6a988dcc7cb53e34244c587fe85d

2017-05-08 09:05 UTC, SshaBrn approved these changes

2017-05-08 09:06 UTC, SshaBrn commented
Sehr gut jetzt passt´s perfekt!

2017-05-08 12:03 UTC, UliVe07 approved these changes

2017-05-08 12:04 UTC, merged