I favoriten button implementieren
schmitzdominic/ProjektSS17 pull request #176
Opened 2017-05-05 19:16 UTC by Xantey

Das Icon in der RecyclerView Bons ist nun klickbar und ändert das Icon. 
Desweiteren habe ich in der C_Bons Funktionen sowie ein Boolean hinzugefügt, um festzuhalten, ob der Button Favorited ist, oder nicht.
Sobald die Bons persistent sind im Tab Bons, sollten die Icons auch richtig zu Beginn ausgelesen bzw gesetzt werden.

Quelle der Icons: https://materialdesignicons.com/ (search tags: star & star-outline)

2017-05-07 13:53 UTC, Sippl requested changes
Hi Marcus, kann die Funktion leider noch nicht testen aufgrund des Minierrors. Kannst du bitte das Icon in Git hinzufügen (siehe Codeanmerkung).

2017-05-07 13:53 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bons_Adapter.java
> +        } else {
Hi Marcus, es wird hier ein Error geworfen. Der Grund ist, dass "star" nicht auffindbar ist. Ich vermute du hast das hinzugefügte Icon in Drawable noch nicht committed&gepushed, dass es für alle in Github verfügbar ist :)

Kein Fehler aber eine Anmerkung bei der Methode "getDrawable". Diese ist deprecated. Wäre es möglich dies auf einem anderen Weg zu lösen? 
Hat das einen gewissen Grund warum diese Icons nicht in dem Mipmap Ordner sonder im Drawable ist?

2017-05-07 14:56 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bons_Adapter.java
> +        } else {
Die Icons sind auch in den MipMap Ordnern. In der Drawable liegt nur eine XML sozusagen. Ja, scheint dann wohl nicht dabei zu sein. Ich schau gleich mal nach und push es, merci 👍

2017-05-07 14:57 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bons_Adapter.java
> +        } else {
So. Drawable ist gepushed. Die MipMap Dateien sollten auch da sein.

2017-05-07 15:03 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bons_Adapter.java
> +        } else {
getResources().getDrawable() ist seit API 21 etwa deprecated. Neue Vorgehensweise: .getDrawable() (ohne Resources davor) - Nur geht es dann nicht für die APIs vor 21, sondern nur für >21. Da wir API Level >15 haben, kommen wir hier in einen Konflikt. Also benutze ich die deprecated schreibweise.

2017-05-08 08:54 UTC, Sippl approved these changes
Für mich passt jetzt soweit alles. Die Funktion funktioniert. Das mit dem deprecated Drawable muss lt. Marcus so bleiben (bzgl. Konflikt).

2017-05-08 11:58 UTC, schmitzdominic approved these changes
Also Marcus... das geht so gar nicht...
:D Spaß beiseite, sehr gut, nur das eine könntest du noch in die obere Zeile einfügen :D

2017-05-08 11:58 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bons_Adapter.java
> +        public ImageView button;
das kann auch über ein komma zur oberen Zeile hinzugefügt werden.

2017-05-08 12:04 UTC, merged