i_favoriten_liste_implementieren
schmitzdominic/ProjektSS17 pull request #196
Opened 2017-05-09 14:10 UTC by ImSeDanny

A_Favoriten:
- Content von A_Garantie kopiert und entsprechend abgeändert --> auf die IDs der box_favoriten_view.xml geändert
- bons.setFavoritent()
- bons.deleteFavorieten()

C_Favoriten_Adapter:
- Klasse erstellt
- Content von C_Garantie_Adapter kopiert und entsprechend abgeändert

box_favoriten_content.xml:
- Content von box_garantie_content.xml kopiert und entsprechend abgeändert

box_favoriten_view.xml:
- Content von box_garantie_view.xml kopiert und entsprechend abgeändert --> IDs auf favoriten geändert

C_Bons_Adapter:
- Favoriten-Sterne mit primary Color getinted

2017-05-09 14:31 UTC, Sippl requested changes
Hi Diddy, bitte noch die Änderungen berücksichtigen (hoffe die haben sich jetzt mit deiner neuen Änderung nicht überschnitten). :-)

2017-05-09 14:31 UTC, Sippl commented on app/src/main/res/layout/box_favoriten_view.xml
> +        android:src="@mipmap/ic_delete_black_24dp"
Hey Diddy, ich finde hier den "Delete" Button sehr irreführend (Auch verwechselbar mit Garantie Liste). Im Home Tab und Bon Tab ist immer ein Stern und plötzlich ein Mülleimer. Meiner Meinung wäre es sinnvoller anstatt dem Mülleimer einen Stern wie im bsp. im Home Tab zu verwenden. Könntest du dies bitte ändern?

2017-05-09 14:31 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Favoriten_Adapter.java
> +            favoriteShopName = (TextView) view.findViewById(R.id.favoriten_view_favoritenbeginn);
Hi Diddy :-), warum hast du hier dies "favoritenbeginn" und drunter "favoritenende" genannt? Kannst du dies bitte in der XML umbennen. Weil das eine ist ja favoriteshopname und das andere favoritedate (im Prinzip das Kaufdatum)

2017-05-09 14:31 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Favoriten_Adapter.java
> +            favoriteDate = (TextView) view.findViewById(R.id.favoriten_view_zusatz_favoritenende);
hier favoritenende

2017-05-09 14:31 UTC, Sippl commented on app/src/main/res/layout/box_favoriten_view.xml
> +        android:id="@+id/favoriten_view_favoritenbeginn"
wie oben bereits erwähnt

2017-05-09 14:31 UTC, Sippl commented on app/src/main/res/layout/box_favoriten_view.xml
> +        android:id="@+id/favoriten_view_zusatz_favoritenende"
wie oben bereits erwähnt

2017-05-10 09:32 UTC, schmitzdominic approved these changes
Ich finds sehr gut. 
PS: Ich mag auch den Mülleimer 👍 
Die Kleinigkeiten hat ja der Fabi schon gefunden, von dem her gibts von mir ein Approve

2017-05-10 16:10 UTC, Sippl approved these changes
Ok grünes Licht

2017-05-11 08:06 UTC, merged