I_budget_verbessern
schmitzdominic/ProjektSS17 pull request #198
Opened 2017-05-14 20:04 UTC by joeymez

Fertigstellung des Items i_budget_verbessern:
                                                                                
Layout
- Anpassung des neuen Layouts in die neue Activity

Button
- Hinzufgen eines Buttons zum speichern
- Beim drücken werden die Inhalte an die nächste Activity weiter gegeben (A_Budget)

Calender
- Hinzufügen eines Kalenders für die Zeitspanne in welches das Budget geplant ist
- weiteres bitte aus Kommentare entnehmen

Logik
- Bevor gespeichert wird, werden alle EditTexts auf vollständigkeit geprüft - ansonsten erfolgt keine Speicherung
- Wenn alle Eingaben korrekt sind werden diese an die nächste Activity weitergegeben (ändert sich wenn DB vorhanden ist)
- Überprüfung ob eingegebener Betrag nicht zu hoch ist - wenn zu hoch wird darauf hingewiesen und nicht gespeichert

HINWEIS: 
- Wunsch zur Änderung des Kreises im Budget konnte diesmal leider nicht berücksichtigt werden. Erfolgt im nächsten Sprint ...
- Clickbare CardView ebenfalls ins nächste Spring
- Anbindung und Auslesung der Daten aus der DB erfolgt ebenfalls im nächsten Sprint

2017-05-14 20:39 UTC, UliVe07 requested changes
Das Eingeben funktioniert bzw. wenn etwas fehlt kommt ein Fehler. 
Nur kommt bei mir am Handy kein Kalender zum Auswählen. 
Bei mehreren erstellten Budgets wird immer das vorherige überschrieben. 
Ansonsten schaut das Layout gut aus.

2017-05-15 07:33 UTC, joeymez commented
Hi @UliVe07 danke für dein Review! Ich kann dir  deine Kommentare beantworten:

- Bezüglich des Kalenders müsstest du ein Doppelklick machen damit es sich ändert da es eine EditText ist
 (Ich habe es jedoch nun auf eine TextView gemacht, sodass es beim ersten Klick aufgeht)

- Bezüglich der CardView selbst werden die eingegebenen Cards nicht gespeichert. Das liegt daran, dass die DB noch existiert und die eingaben somit dynamisch und nur Testdaten sind. Daher nicht wundern wenn Sie nicht da sind. Ich könnte eine Test-DB bauen aber das wäre den Aufwand nicht wert. D.h. dieser "BUG" ist kein Bug sondern lediglich eine kurze Sicht auf das Ergebnis was nach der Eingabe erfolgen soll :)

2017-05-15 11:10 UTC, UliVe07 approved these changes

2017-05-15 19:26 UTC, Sippl approved these changes
Super sieht gut aus, Den erwähnten Bug mit den Punkt eingeben beim Budget hinzufügen hast ja bereits behoben :). Kleinere Optische Sachen können wir ja morgen diskutieren. Super :)

2017-05-15 20:14 UTC, merged