i_datenbank_erweitern
schmitzdominic/ProjektSS17 pull request #209
Opened 2017-05-19 15:36 UTC by schmitzdominic

IMPLEMENTIERT:

- Datenbank erweiterungen (Budget)
- Budget überarbeitet und an die DB angebunden
- Sämtliche Recycler views überarbeitet
- Floating-Buttons verschwinden nun beim scrollen ( NICHT auf HOME und STATISTIK Tab)

2017-05-21 11:53 UTC, ImSeDanny approved these changes
Sieht gut aus!
Mir sind soweit keine Fehler aufgefallen

2017-05-21 15:24 UTC, joeymez requested changes

2017-05-21 15:24 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
Wenn die Methode nichts macht dann bitte löschen! :)

2017-05-22 07:18 UTC, joeymez approved these changes
Alles klar! Code scheint zu passen :)

2017-05-22 13:48 UTC, merged