i_bon_anzeigen_verbessern
schmitzdominic/ProjektSS17 pull request #233
Opened 2017-05-25 14:29 UTC by joeymez

Abschließen des Items i_bon_anzeigen_verbessern:

Layout:
- komplette Überarbeitung des Layouts
- Hinzufügen neuer Titel für die Inhalte
- Hinzufügen neuer Farben (z.B. primarySecondary für die CardView - Header)

Logik:
- Keine Änderung in der Logik

BugFix:
- Fixen des Bugs, welches die Artikel nicht gezeigt hat (Name + Preis)

Hinweis: Ist zwar die erste Version, würde Sie jedoch in Zukunft etwas umgestalten. Mehr dazu in der Review am Dienstag! ;)

2017-05-25 15:01 UTC, Xantey requested changes
Sehr gute Arbeit, läuft alles! Sieht gut aus, bin mal gespannt wie es mit richtigem Logo aussieht. Hier müssen wir bitte auf die Qualität der Logos achten, da sie sonst total scheiße aussehen könnten! 
Ein paar Änderungen hab ich gefunden, aber nichts großes.

2017-05-25 15:01 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                    holderBottom.preis.setText(Double.toString(artikel.get(getArticleIndex()).getPrice()) +" €");
Hier bitte ebenfalls. Generell hardcoded Code anmerken, damit wir ihn später mal leicht finden.

2017-05-25 15:01 UTC, Xantey commented on app/src/main/res/layout/box_bons_view_layout.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
Diese Zeile bitte verschieben um 3 Zeilen nach oben. So dass es direkt unter dem anderen "xmlns:android=..." steht. 

_Ist das richtig, dass es als "xmlns:app" aufgerufen wird und nicht als "xmlns:android" nachdem ich darunter keine "app:..." aufrufe sehe. Kann aber auch sein, dass man es so für die AppBar oder ähnliches braucht._

2017-05-25 15:07 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                if (!bon.getPath().equals("PFAD")) {
Gut das du es erwähnst. Wie du jedoch anhand meines PR-Kommentars entnehmen kannst, habe ich an der Logik nichts geschrieben bzw. verändert. `Dieser Teil des Codes hat entweder der Alex oder der Domi hinzugefügt. Für weitere Anmerkungen daher bitte an einer der beiden wenden :)`

2017-05-25 15:09 UTC, joeymez commented on app/src/main/res/layout/box_bon_anzeigen_bottom_content.xml
> +            android:text="X02.0X €" />
Nein das sind einfach Default-Strings  ... ich hätte sie auch "Kackwurst" nennen können ... Der Wert der hier drin steht ist jedoch eh egal, da diese bei der Befüllung der RecyclerView mit den jeweiligen Daten der Bons überschrieben werden.

2017-05-25 15:10 UTC, joeymez commented on app/src/main/res/layout/box_bon_anzeigen_header_content.xml
> +            android:textSize="14sp"
dp verwendet man bei Objekten (d.h. layouts) ... sp ist Standard für schriften :)

2017-05-25 15:11 UTC, joeymez commented on app/src/main/res/values/colors.xml
> +    <!-- Johanns Farben
Ich streiche es mal raus :)

2017-05-25 15:11 UTC, joeymez commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Das sind Code-Teile die der Domi zu beginn geschrieben hat. Daher weiß ich nicht ob die raus sollen :)

2017-05-25 15:12 UTC, joeymez commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Auch hier wieder die selbe Sache. Das sind alte Codeteile die ich nicht entwickelt habe.... Daher bitte an den jeweiligen wenden. Werde es dennoch erstmal drin lassen. Im Notfall kann man es selbst löschen ...

2017-05-25 15:12 UTC, joeymez commented on app/src/main/res/values/strings.xml
> +    <string name="bon_anzeigen_gesbetrag">XOOCB.00 €</string>
siehe oberen Kommentar :)

2017-05-25 15:13 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            if(!bon.getPath().equals("PFAD")) {
siehe oberen Kommentar ;)

2017-05-25 15:14 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +        //Hier muss das Array eigebtlich um 1 Hochgezählt werden jedoch stürzt dann die App ab
Den Bug habe ich behoben... der Counter war auskommentiert und hat daher nicht hochgezählt. Sollte nun alles passen :)

2017-05-25 15:15 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +        //Hier muss das Array eigebtlich um 1 Hochgezählt werden jedoch stürzt dann die App ab
Alles klar, dann streich das bitte alles raus, dass es nachträglich nicht zu verwirrungen führt.

2017-05-25 15:15 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                holderHeader.gesbetrag.setText(df.format(gesBetrag)+" €");
jo werde es hinzufügen

2017-05-25 15:15 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                    holderBottom.preis.setText(Double.toString(artikel.get(getArticleIndex()).getPrice()) +" €");
auch hier das selben wie oben :)

2017-05-25 15:16 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                if (!bon.getPath().equals("PFAD")) {
Okay, dann ändert das eben einer von den beiden. Aber es muss definitiv geändert werden 😄 Wie wir das nun handhaben weiß ich nicht. Das andere Item besteht ja nicht mehr, oder?

2017-05-25 15:17 UTC, Xantey commented on app/src/main/res/layout/box_bon_anzeigen_bottom_content.xml
> +            android:text="X02.0X €" />
Okay, also werden die "X" später auch als "X" angezeigt (falls man keine Default im Code setzen würde)? Dachte iwie das wäre etwas spezielles 😄

2017-05-25 15:17 UTC, Xantey commented on app/src/main/res/layout/box_bon_anzeigen_header_content.xml
> +            android:textSize="14sp"
Alles klar, danke! 👍

2017-05-25 15:17 UTC, Xantey commented on app/src/main/res/values/colors.xml
> +    <!-- Johanns Farben
Merci 👍

2017-05-25 15:18 UTC, Xantey commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Dann müssen wir ihn mal fragen, ansonsten raus damit 👍 
@schmitzdominic Geht das, wenn ich dich hier markiere? 😄

2017-05-25 15:19 UTC, Xantey commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Dann bitte in Slack fragen. Würde das nur ungern so mergen. Am ende haben wir endlos viel dummy Code drinnen und keiner weiß wozu der gut ist.

2017-05-25 15:19 UTC, joeymez commented on app/src/main/res/layout/box_bons_view_layout.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
dieses Layout war nicht Teil meines Items und wurde daher nicht berücksichtigt. Das Layout gehört der Activity A_Tab3_Bons und nicht der Activity A_Bon_Anzeigen. Ich kann es aber schnell ändern wenn gewünscht ;)

2017-05-25 15:20 UTC, Xantey commented on app/src/main/res/layout/box_bons_view_layout.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
Ja das wäre super, vielen Dank 👍

2017-05-25 15:22 UTC, joeymez commented on app/src/main/res/layout/box_bon_anzeigen_bottom_content.xml
> +            android:text="X02.0X €" />
jo genau. Wenn diese TextView nicht befüllt wird kommt halt dieser Default-String. Aber wenn ihr umbedingt was anderes stehen haben wollt sagt mir Bescheid ;)

2017-05-25 15:27 UTC, Xantey commented on app/src/main/res/layout/box_bon_anzeigen_bottom_content.xml
> +            android:text="X02.0X €" />
Nein, das ist schon in Ordnung, hab mich nur gewundert, ob hier ein Austausch mit Code stattfindet. 👍

2017-05-25 15:27 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Bon_Anzeigen_Adapter.java
> +                if (!bon.getPath().equals("PFAD")) {
Wurde der String XML hinzugefügt :)

2017-05-25 15:28 UTC, joeymez commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
Ich habe es entfernt! :)

2017-05-25 15:28 UTC, joeymez commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
auch hier habe ich die unnützen String XML entfernt :)

2017-05-25 15:35 UTC, joeymez commented
@Xantey Deine Änderungswünsche wurden berücksichtigt:

- unnötige String-XML wurden entfernt
- einige feste Strings wurder der String-XML hinzugefügt (z.B. PFAD)
- ToDo-Kommentare wurden hinzugefügt (€")

2017-05-26 13:23 UTC, joeymez commented
@schmitzdominic muss nun noch etwas verändert werden oder ist diese Version nun fertig zum mergen? :)

2017-05-26 14:08 UTC, schmitzdominic commented
@joeymez Jetzt dürfte sie fertig sein. Also die Reviewer können nochmal drüber schauen ;)

2017-05-27 21:23 UTC, SemperF1 approved these changes
Schaut wirklich gut aus. Code schaut gut aus, mit is nix aufgefallen was nicht passt. Weitere Bugs sind mir auch nicht aufgefallen.

2017-05-28 11:52 UTC, Xantey approved these changes

2017-05-28 12:14 UTC, UliVe07 approved these changes
Schaut super aus ;) 
mir sind zusätzlich zu den schon gefixten Sachen keine Fehler mehr aufgefallen. 
Im Code passt soweit auch alles. 
Gute Arbeit!

2017-05-29 12:04 UTC, merged