i_garantie_save_bug
schmitzdominic/ProjektSS17 pull request #234
Opened 2017-05-25 19:29 UTC by Xantey

Leute, ich bin durch damit. Hab nun Stunden zig verschiedene Lösungen implementiert und es geht immer noch nicht richtig. Das Datum wird korrekt gesetzt, meine Methode dies zu ändern funktioniert auch und mein StringBuilder baut einen String "23-06-2021", welchen ich mir ausgeben konnte. Diesen setze ich anschließend in setGuaranteeEnd und in Garantie wird er mit getGuaranteeEnd wieder geholt. Aber jetzt sieht er plötzlich so aus "2021.06.23". Ich find die Stelle nicht, an der das passiert. 

Komisch ist auch, dass ich fast keine Logs ausgegeben bekomme...

2017-05-25 20:03 UTC, schmitzdominic commented
Bug wurde gefixt :D

2017-05-27 13:53 UTC, Sippl requested changes
Hi Marcus & @schmitzdominic, bei mir scheint es richtig zu laufen. Er hat bei mir das Datum richtig gesetzt wenn ich einen Bon anlege, Garantie zuweise und in Garantie nach dem Bon nachschaue. 

Paar kleine Anmerkungen hätte ich noch, sonst gäbe es nen dickes Approve! Super gemacht Markus und Domi!

2017-05-27 13:53 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        Log.e("LOG", saveBon.toString());
Kann der Log nicht raus?

2017-05-27 13:53 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Adapter_Garantie.java
> +            warrantyShop = (TextView) view.findViewById(R.id.garantie_view_garantiebeginn);
Wenn das Datum hier nicht mehr angezeigt werden soll "WarrantyBeginn" und ersetzt wurde durch WarrantyShop (Shopname), dann wäre es gut, auch in XML die Id für dieses Feld anzupassen (Garantiebeginn hier noch).

2017-05-27 13:53 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Adapter_Garantie.java
> +        Log.e("ADAPTER GARANTIE","" + bon.getGuaranteeEnd());
Kann der Log hier raus?

2017-05-27 13:53 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +        /*Log.e("######### DB LAEDEN","#########################################");
Für was sind diese Funktionen? Wenn sie ausgekommentiert sind? Werden sie noch benötigt?

2017-05-28 14:12 UTC, dontcallme requested changes
Bei mir wird der Garantie Zeitraum jetzt korrekt angezeigt, gut gemacht  Marcus und Domi. Außer den auskommentierten Codezeilen und den Logs hab ich jetzt auch nichts entdeckt. Approve gibts dann bei beseitigung der genannten Stellen.

2017-05-28 14:12 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        Log.e("LOG", saveBon.toString());
Gleiche Frage von mir^^

2017-05-28 14:12 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
Bin der gleichen Meinung wie Fabi, wird das noch gebraucht oder kann das weg. :)

2017-05-29 11:52 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        Log.e("LOG", saveBon.toString());
Nein der Log ist wichtig :)
Der ist nur dafür da um vor dem Speichern noch einmal zu überprüfen ob die Daten richtig übernommen wurden.

2017-05-29 12:03 UTC, schmitzdominic commented
Hey Leute, habs geändert :)

2017-05-29 13:58 UTC, Sippl approved these changes

2017-05-29 15:17 UTC, merged