i_home_überarbeiten
schmitzdominic/ProjektSS17 pull request #236
Opened 2017-05-27 14:02 UTC by joeymez

** Fertigstellung des Items i_home_überarbeiten **

HINWEIS: BITTE liest meine Kommentare im Code damit es hier im PR nicht zu unnötigen Commis kommt! Danke ;)

Layout:
- Verwerfung aller vorherigen Layouts und hinzufügen neu gestalteter Layouts
- Formatierung der Layouts als CardView in einer Recycler View
- Layout 1 (Anzeige letzter drei Bons); Layout 2 (Anzeige letztes Budget); Layout 3 (Anzeigen eines Graphs)

Logik:
- Verwerfen der gesamten alten (verbuggten) Logik und Implementierung einer neuen Logik
- Daten werden nun dynamisch aus der DB gelesen (sofern vorhanden) - natürlich in Zukunft änderbar
- Hinzufügen einiger Hilfs-Funktionen zum Verarbeiten der Daten in der RecyclerView

Sonstiges:
- Favoriten-Button sind klickbar und bewirken auch Änderung in der DB
- In Zukunft sollen die anderen CardViews ebenfalls klickbar sein (jedoch nicht in diesem Sprint!)

INFO: Die Implementierung zum Klicken der Buttons, welche die neue Activity zum Anzeigen der Bons aufruft wurde hier erstmal NICHT berücksichtigt. Der Grund hierfür ist, dass das Item Bon_Anzeigen parallel in diesem Sprint überarbeitet wurde und es somit Überschneidungen gegeben hätte.
Es ist alles vorbereitet, sodass nur noch ein Intent zwischen beiden erfolgen muss! :)

2017-05-28 11:24 UTC, ImSeDanny approved these changes
sieht gut aus, von mir gibts daher eine approve

2017-05-28 11:41 UTC, schmitzdominic requested changes
Hi Johanns,
kannst du bitte noch unter "Wichtigste Budgetplanung", den Tag anzeigen? Momentan wird 2x das Jahr ausgegebene ;) Danke :)

2017-05-28 11:52 UTC, Sippl requested changes
Kleine Annmerkungen. (Das mit dem Budget Layout hat bereits Domi glaub genannt).

2017-05-28 11:52 UTC, Sippl commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +    <ImageView
Kann das ausgekommentierte nicht raus? Für was ist dies noch drinnnen? :-)

2017-05-28 11:52 UTC, Sippl commented on app/src/main/res/layout/box_home_topbudget_layout.xml
> +                android:id="@+id/relativeLayout2"
Bitte ID's immer eindeutig nennen.

2017-05-28 11:52 UTC, Sippl commented on app/src/main/res/layout/box_home_topbudget_layout.xml
> +                    android:id="@+id/textView2"
Bitte ID's immer eindeutig nennen.

2017-05-28 11:52 UTC, Sippl commented on app/src/main/res/layout/box_home_topbudget_layout.xml
> +                    android:id="@+id/textView15"
Bitte ID's immer eindeutig nennen.

2017-05-28 11:52 UTC, Sippl commented on app/src/main/res/layout/box_home_topbudget_layout.xml
> +    <RelativeLayout
Das kommentierte kann eigentlich raus? Oder für was wird das benötigt?

2017-05-28 13:56 UTC, dontcallme requested changes
Neben dem was Fabi und co. schon angemerkt haben, ist mir noch aufgefallen (sry falsch ich ein Kommentar dazu übershen hab), dass die unterste Statistik von dem Floating button überdeckt wird. Hier wäre es gut wenn man noch ein wenig höher scrollen könnte sodass diese nicht mehr verdeckt wird.

Ansonsten gilt zu sagen, gut gemacht, sieht gut aus :)

2017-05-28 13:56 UTC, dontcallme commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
Alle Bons sind statisch angelegt richtig?, da sheißt wenn erst 1 Bons eingescannt wurde werden die anderen beiden als Default angezeigt oder?

2017-05-28 13:57 UTC, dontcallme commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
ich seh grad das er den schnipsel nicht richitg rausgenommen hat, sry dafür, aber ich denke du weiß was ich mein ^^

2017-05-28 14:12 UTC, joeymez commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +    <ImageView
jo ich nehme es raus :)

2017-05-28 14:13 UTC, joeymez commented on app/src/main/res/layout/box_home_topbudget_layout.xml
> +                android:id="@+id/relativeLayout2"
@Sippl kann ich machen .... habe ich nicht geändert bzw. gemekrt, da dieser Teil des Codes von jemand anderen geschrieben wurde

2017-05-28 14:14 UTC, joeymez commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
ne ich weiß ehrlich gesagt nicht was du meinst? xD

2017-05-28 19:21 UTC, dontcallme commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
Damit war gemeint das in der Card view 3 plätze für bons sind, was ist wenn es nur 1 bon gibt?, ist jetzt nicht so wichtig aber wollts halt wissen xD

2017-05-29 10:44 UTC, dontcallme approved these changes

2017-05-29 13:19 UTC, Xantey commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
Ich glaube durch unsere Default Werte in der Main, kann es dazu nicht kommen. Wobei ich nicht weiß, ob wir später in der fertigen App default Bons erstellen, eigentlich macht das keinen Sinn, wodurch Domis Frage berechtigt ist. Wir sollten das auf jeden Fall vermerken oder direkt lösen!

2017-05-29 13:20 UTC, Xantey commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
@joeymez @dontcallme

2017-05-29 15:18 UTC, schmitzdominic approved these changes

2017-05-29 15:18 UTC, schmitzdominic commented
Danke nochmal für die Überarbeitung 👍

2017-05-29 15:19 UTC, joeymez commented on app/src/main/res/layout/box_home_boncard_layout.xml
> +
ich habe den Bug gefixt. D.h. die HomeCards werde erst angezeigt, wenn drei Bons und mind. ein Budget existieren. Wenn nicht ist die Home Leer!

Das Item wird im nächsten Sprint Dynamisch gemacht und  finalisiert :)

2017-05-29 15:19 UTC, merged