i_kamera_ocr_verbessern
schmitzdominic/ProjektSS17 pull request #237
Opened 2017-05-27 15:19 UTC by schmitzdominic

IMPLEMENTIERT:

- Weiteren Algorithmus implementiert
- Logo implementiert
- DBHandler erweitert um die Statistiken befüllen zu können.
- Gruppenfunktion auskommentiert
- Regex ausdrücke implementiert

BEACHTE:
Der Algorithmus funktioniert leider noch nicht einwandfrei. Muss nochmal ggf. angepasst, verändert werden.

2017-05-28 13:07 UTC, Sippl requested changes
Nur das wie angesprochen, Code ist bereits durchgeschaut und passt soweit, DB_Handler habe ich die neuen Funktionen getestet und funktioniert einwandfrei, OCR werde ich noch testen (muss erstmal Bons suchen)

2017-05-28 13:07 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_DatabaseHandler.java
> +
Bitte hier noch ein Kommi :D

2017-05-28 15:32 UTC, joeymez requested changes
Habe mir dein Code angeschaut. Schaut gut aus bis auf einige Kleinigkeit. Neben den bereits vom Fabi erwähnten Punkten müssen auskommentierte Sachen raus genommen werden, um unnötigen Code zu verhindern :)

2017-05-28 15:32 UTC, joeymez commented on app/src/main/res/menu/menu_main.xml
>  </menu>
Auskommentiertes bitte rausnehmen .. ist sonst unnötiger Code :)

2017-05-29 11:29 UTC, joeymez approved these changes

2017-05-29 11:45 UTC, Sippl approved these changes
Hi Domi, von mir gibts nun ein approve, jedoch wie bereits angesprochen konnte ich noch kein Bon korrekt abfotografieren. Sehr oft stürzt dabei BonPix ab, manchmal nicht, dann kommt jedoch "kein Kassenzettel gefunden oder so".

2017-05-29 13:57 UTC, merged