i_roundebitmap_fix
schmitzdominic/ProjektSS17 pull request #267
Opened 2017-05-31 06:46 UTC by ImSeDanny

Code wurde bei foglenden Adaptern geändert
- C_Adapter_Bons
- C_Adapder_Favoriten
- C_Adapter_Garantie
- C_Laeden_Adapter

folgende Zeile wurde eingefügt:
  holder.icon.setImageBitmap(S.getShopIcon(holder.res, bon.getShopName()));

Anmerkung:
- bei C_Laeden_Adapter konnte  folgende Zeile nicht implementiert werden
  holder.icon.setImageBitmap(S.getShopIcon(holder.res, bon.getShopName()));
   --> die Variable "bon" wird nicht erkannt und es gibt eine Fehlermeldung
   --> habe sie daher auskommentiert und alten Code stehen lassen

2017-05-31 07:57 UTC, Sippl requested changes
Hallo Diddy, 

habe Code und App getestet, in C-Adapter-Bons, Favoriten, Garantie sieht es passend aus. 

Deine Anmerkung:
"Anmerkung:
    bei C_Laeden_Adapter konnte folgende Zeile nicht implementiert werden
    holder.icon.setImageBitmap(S.getShopIcon(holder.res, bon.getShopName()));
    --> die Variable "bon" wird nicht erkannt und es gibt eine Fehlermeldung
    --> habe sie daher auskommentiert und alten Code stehen lassen
"

Das kann ich so nicht gelten lassen. Wir haben doch vereinbart, dass nur ein Pull Request gestellt werden darf, wenn dieser auch funktioniert und deiner Meinung nach fertig ist. Es ist doch normal, dass hin und wieder etwas nicht funktioniert und Fehler geworfen werden,, aber diese müssen halt behoben werden. Hast du dir diesen Adapter komplett angeschaut? In diesem ist doch klar das kein C_Bon bon vorkommt, da es sich hierbei um die Laden liste und nicht um die Bon liste dreht. Bitte nicht nur das vom Domi Copy & Pasten, sondern auch versuchen es zu verstehen, was dort gemacht wird :-)

Du musst doch einfach nur bon.getShopName(), mit der Methode für die shops austauschen
 holder.iconShop.setImageBitmap(S.getShopIcon(holder.res, shop.getName()));

Passe es bitte an und dann sollte es klappen :D ;) (Bitte vergewissere dich noch einmal ob du es in jedem relevanten Adapter angepasst hast)

2017-05-31 07:57 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/daten/C_Laeden_Adapter.java
> +        //holder.icon.setImageBitmap(S.getShopIcon(holder.res, bon.getShopName()));
Das kann ich so nicht gelten lassen :D Ist doch klar,  das hier kein bon geht, wenn die Variable in diesem Adapter gar nicht vor kommt.

2017-05-31 13:59 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Laeden_Adapter.java
> +        //holder.icon.setImageBitmap(S.getShopIcon(holder.res, bon.getShopName()));
@ImSeDanny  bitte nächstes mal nicht einfach den bereits vorgegbenen Code wild  "Copy & Pasten"! Natürlich bleibt die Logik die selben, dennoch musst du den Code auf den jeweiligen Programmstück anpassen!

INFO: Nächsten mal Hirn einschalten (nicht böse gemeint!)  ;)

2017-06-02 10:46 UTC, Sippl approved these changes
Passt für mich so.

2017-06-05 11:27 UTC, merged