i_spinner_icon_implementieren
schmitzdominic/ProjektSS17 pull request #269
Opened 2017-05-31 17:30 UTC by dontcallme

Sobald im spinner ein Laden ausgewählt wurde, wird das passende Icon neben dem spinner angezeigt.

2017-05-31 17:34 UTC, Sippl requested changes
HI domi, Bitte kein RoundedbitmapDrawable verwenden. Kannst dich an Diddy's Pull Request anlehen (Achtung Änderungen sind aber Nötig.

2017-05-31 17:34 UTC, Sippl commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                    RoundedBitmapDrawable roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(getResources(), imageBitmap);
HI domi, Bitte kein RoundedbitmapDrawable verwenden. Kannst dich an Diddy's Pull Request anlehen (Achtung Änderungen sind aber Nötig.

2017-05-31 18:05 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                    RoundedBitmapDrawable roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(getResources(), imageBitmap);
Hi Fabi,
das ist nicht korrekt. Wir benötigen es wegen dem Tint.
PS: Domi man kann es doch in einer Zeile schreiben ;)
`((ImageView) findViewById(R.id.ocr_manuell_image_view_shop)).setImageDrawable(RoundedBitmapDrawableFactory.create(getResources(), S.getShopIcon(getResources(), bon.getShopName())));`

2017-05-31 18:09 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                    RoundedBitmapDrawable roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(getResources(), imageBitmap);
Ok, wurde angepasst. Seht es euch bitte nochmal an ob es jetzt passt.

2017-05-31 18:14 UTC, Sippl commented
Sorry mein Fehler :-)

2017-06-01 00:11 UTC, Sippl approved these changes
Passt bei mir jetzt so! (Jedoch ist mir ein Bug im Spinner aufgefallen, der hat aber nichts mit deinem Item zu tun und wurde auch nicht durch dein Item ausgelöst, dennoch merke ich es hier zudem an, da es mir hier aufgefallen ist / Und zwar: Wenn ich Spinner "Hinzufügen klick" und egal ob ich was eingebe oder nicht, anstatt cancel oder speichern auserhalb dem spinner auf den Bildschirm klicke, verschwindet der Spinner und es steht "Hinzufügen" drinnen. Und man kommt nur über Umwege zurück zum Spinner.

2017-06-01 14:15 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                    RoundedBitmapDrawable roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(getResources(), imageBitmap);
@dontcallme @schmitzdominic 
Warum RoundedBitmapDrawableFactory? 

**Bitte mal so versuchen:**
`((ImageView) findViewById(R.id.ocr_manuell_image_view_shop)).setImageDrawable(new BitmapDrawable(getResources(), S.getShopIcon(getResources(), bon.getShopName())));`

2017-06-02 10:48 UTC, Sippl commented
Bug wurde bereits behopen.

2017-06-05 12:39 UTC, ImSeDanny approved these changes
Kann gemerged werden, Icons werden angezeigt

2017-06-05 16:08 UTC, merged