i_notifications_logik
schmitzdominic/ProjektSS17 pull request #271
Opened 2017-06-01 11:28 UTC by UliVe07

If Statement hinzugefügt, dadurch ist ein Fehler aufgetreten True und False wurde falsch anzgezeigt daher konnte die Notifikation nicht überprüft werden -> Dieser Fehler wurde gelöst
Mit dem Aufruf von der SendNotification können die Reviewer testen, ob es beim Abwählen des Hakens in den Einstellungen nicht angezeigt wird.

2017-06-01 14:07 UTC, Xantey requested changes
Mir ist noch etwas aufgefallen, ansonsten gute arbeit! 👍

2017-06-01 14:07 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/fragments/F_Einstellungen.java
> +            S.prefs.savePrefBoolean(KEY_NOTE, sharedPreferences.getBoolean(KEY_NOTE, true));
Diese Zeile verstehe ich nicht. 
Ich verstehe was hier passiert, aber nicht, warum ihr das macht?

2017-06-01 14:07 UTC, Xantey commented on app/src/main/res/values/strings.xml
> +    <string name="einstellungen_notification_text">Aktivieren oder Deaktivieren der Notifications</string>
Können wir das bitte auf Deutsch ändern

2017-06-01 14:25 UTC, UliVe07 commented on app/src/main/res/values/strings.xml
> +    <string name="einstellungen_notification_text">Aktivieren oder Deaktivieren der Notifications</string>
des hab ich ja extra auf deutsch geändert 
Gut wenns dich stört könnt ich noch des c durch n k ersetzen aber der rest ist ja deutsch

2017-06-01 14:25 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/fragments/F_Einstellungen.java
> +            S.prefs.savePrefBoolean(KEY_NOTE, sharedPreferences.getBoolean(KEY_NOTE, true));
des war im Zuge von dem Fehler dass der nicht mehr vorkommt

2017-06-01 14:32 UTC, Xantey commented on app/src/main/res/values/strings.xml
> +    <string name="einstellungen_notification_text">Aktivieren oder Deaktivieren der Notifications</string>
Notifications ist Deutsch? Das sollte eher zb "Benachrichtigungen" heißen, oder? Meine Mum zum Beispiel hätte kein Plan, was das heißen soll 😄

2017-06-01 14:35 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/fragments/F_Einstellungen.java
> +            S.prefs.savePrefBoolean(KEY_NOTE, sharedPreferences.getBoolean(KEY_NOTE, true));
Mhm, das ist aber nicht so gut. Könntest du den Bug den du hattest näher erklären? Denn die Prefs sind schon persistent, du brauchst diese also nicht nochmal extra Speichern in der Regel. Diese Methoden in der "S" sind eigentlich für Values außerhalb der Einstellungen gedacht.

2017-06-01 14:37 UTC, UliVe07 commented on app/src/main/res/values/strings.xml
> +    <string name="einstellungen_notification_text">Aktivieren oder Deaktivieren der Notifications</string>
ok gut überzeugt 😄

2017-06-01 16:42 UTC, Xantey approved these changes

2017-06-01 16:45 UTC, Xantey commented
Bug ist gefixed. Bitte erneut testen, ob Notification richtig ausgelöst wird.

2017-06-05 13:24 UTC, SemperF1 approved these changes

2017-06-05 13:25 UTC, SemperF1 commented
Habe vergessen zu Schrieben. Passt alles.

2017-06-05 16:07 UTC, merged