i_home_finalisieren
schmitzdominic/ProjektSS17 pull request #272
Opened 2017-06-05 11:05 UTC by joeymez

Fertigstellung des Items i_home_finalisieren:

HINWEIS: 
- Hauptreviewer: @UliVe07 
- Zweitreviewer: @dontcallme 
- Um einen reibungslosen Test zu gewährleisten BITTE die alte App löschen und die neue eiinspielen!:)

Layout:
- minimal Änderung im Layout und im Design (Farben, etc.. )
- Hinzufügen eines Default-Layouts für eine CardView (Verwendung wenn noch keine Daten bestehen)

Logik:
- Umbauen der Logik 
- Hinzufügen neuer Layout-Logiken für Default-Cards & vorhandene Cards
- Hinzufügen von neuen Funktionen zur Vorbereitung von Daten 

Cards:
- Liste der ersten Card ist nun dynamisch und wird je nach Anzahl der Bons befüllt (Max. jedoch 3 ... auch höher einstellbar)
- Zweite Card wird nun entsprechend der Voreinstellung im Budget ("Hacken" setzen) auf der Home angezeigt und automatisch berechnet
- Dritte Card zeigt nun die Letzten eingescannte Bons (wie erste Cards) in einem Liniendiagramm an. Hierbei dient diese nur als grobe Übersicht, NICHT als detaillierte Kostenübersicht!!! Entsprechend der Bons wird der Laden angezeigt, an welchem dieser entstand

Bugfixing:
- Umschreibung der Funktion zum Auslesen der neuesten Bons (DBHandler)
- Umschreibung der Abfragen zum Anzeigen des Budgets

2017-06-05 12:46 UTC, Xantey commented
_"Liste der ersten Card ist nun dynamisch und wird je nach Anzahl der Bons befüllt (Max. jedoch 3 ... auch höher einstellbar)"_

Wäre es nicht nice, wenn wir das als Einstellung in den Einstellungen hätten? Dass der User selbst wählen kann.

2017-06-05 14:22 UTC, dontcallme requested changes
Bitte noch die Anpassungen aus dem Change Request und meinem Kommentar ändern. 

1. Budget card lässt sich hinzufügen, aktualisert aber nicht wenn man die Bons wieder löscht. (hab z.B 45€ gesamt angegeben und 2 bons mit 3 und 7 || nach löschen eines oder beider Bons steht da immer noch 35)
2. ist es Absicht das auf dem Home Tab das ursprüngliche Budget nicht angezeigt wird?

2017-06-05 14:22 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>          }
Bitte um erklärung was lalaal und so hier drinn machen?

2017-06-05 14:22 UTC, dontcallme commented on app/src/main/res/values/strings.xml
> +    <string name="tab_home_chartcard_budget_default_content"> Fürgen sie zuerst ein Budget hinzu ...</string>
Bitte Schreibfehler korrigieren, danke.

2017-06-05 14:35 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>          }
@schmitzdominic ein Fall für dich ;)

2017-06-05 14:46 UTC, joeymez commented
@Xantey bezüglich der Anzahl der Bons steht das Attribut (bonsCount) für jeden zur Verfügung. Wenn man es über die Einstellungen ändern möchte wäre es eine gute Idee. Jedoch fällt dies meiner Meinung nach nicht in unser Item mit rein. Daher bitte im nächsten Sprint irgendwo reinbauen ;)

2017-06-05 16:04 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>          }
@dontcallme Das heißt das mir das sonstige Feld in den Dummy Daten lalalala sagt :D können auch test123 rein schreiben ;)

2017-06-05 16:29 UTC, Xantey commented
@joeymez Okay. Aber dann müssen wir uns das vormerken! 👍

2017-06-05 16:49 UTC, joeymez commented
@dontcallme bezüglich deinen Anmerkungen:

1. Schreibfehler wurden behoben
2. Chart nicht mehr zoombar
3. Chartwerte auf der linken Seite (Ausgaben in €) sind nun angepasst

Info: Die Sache mit dem Budget regelt der @schmitzdominic  :)

2017-06-05 23:18 UTC, dontcallme requested changes
Hi Johanns, danke für die Anpassung.
Hab leider noch ein Problem festgestellt.
Bei Budget werden nur die Bons mit dem von Datum berücksichtigt und nicht der von bis Zeitraum.

Grafik passt soweit, ich find nur nicht so schön das die Daten Random und nicht chronologisch angezeigt werden + Bei anfangs kleinen Beträgen z.B nur 1 Bon mit 3€ kommt die 0 doppelt vor. Vlt. gibts da ne Lösung.

Ansonsten gut gemacht :)

2017-06-06 14:15 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>          }
Ok, nee passt schon :)

2017-06-06 19:15 UTC, dontcallme commented
Hey Uli, schau dir das ganze bitte auch nochmal an, danke.

2017-06-07 07:52 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Tab1Home.java
> -        if(S.dbHandler.getAllBons(S.db).size() > 2 && S.dbHandler.getAllBudgets(S.db).size() > 0) {
Eine Frage, Warum wurde hier das If-Statement entfernt?

2017-06-07 07:56 UTC, UliVe07 reviewed
Zum Code habe ich eine kleine Frage, habs aber als Comment eingefügt.
Bei mir funktioniert alles. Ich habe 4 Bons hinzugefügt es werden nur die drei aktuellsten angezeigt. Außerdem hab ich ein Budget erstellt in dem nur 3 von den 4 Bons berücksichtigt werden sollen -> Funktioniert auch. 
Wenn ich einen Bon im Budget lösche überschreibt er den Betrag und passt den an -> Perfekt. 
Das einzige was mir noch aufgefallen ist, dass der Name vom Budget nicht auf dem Home Screen angezeigt wird. War das so geplant oder ist damit ein größeres Problem verbunden? Wenn das geklärt ist gibts von mir ein Approve. 
Ansonsten super Arbeit Johanns.

2017-06-07 11:19 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/A_Tab1Home.java
> -        if(S.dbHandler.getAllBons(S.db).size() > 2 && S.dbHandler.getAllBudgets(S.db).size() > 0) {
@UliVe07  Diese Abfrage wurde hinzugefügt um eine Null Pointer Exception zu verhindern. Da wir dieses Problem jedoch bereits behoben haben, konnte diese Abfrage entfernt werden :)

2017-06-07 11:23 UTC, joeymez commented
@UliVe07 Bezüglich der 3 Bons ... Es war geplant das nur 3 (in Zukunft über Einstellungen einstellbar) Bons angezeigt werden. Die Anzahl kann erhöht werden durch ein Attribut. Wird jedoch zunächst bei 3 bleiben!

Der Titel des Budget sollte nicht angezeigt werden. Wenn wir das einfügen wollen wäre das kein Problem und auch kein großer Aufwand. Das eigentliche Problem wäre nur, dass wir zwei Titel (Titel der Card & Titel des Budgets) untereinander haben würden und das finde ich persönlich nicht so schön :)

Das können wir aber im Review nochmal besprechen und hat mit der eigentlichen Logik nichts zu tun ^^

2017-06-07 11:39 UTC, UliVe07 approved these changes
Das mit den drei Bons war eine Feststellung dass es passt. Nur ein bisschen falsch formuliert. 
Wegen der Überschrift passt das dann wollte nur wissen ob du dir dadrüber schon Gedanken gemacht hast. 
Somit Approve. Wirklich gute Arbeit!

2017-06-07 11:55 UTC, dontcallme approved these changes
Danke euch, sieht gut aus und funktionier auch alles. Top :)

2017-06-07 16:08 UTC, merged