i_main_tabs_tutorial
schmitzdominic/ProjektSS17 pull request #276
Opened 2017-06-10 14:03 UTC by dontcallme

Hey Zusammen, hier der Pull Request zu i_main_tabs_tutorial.

Beschreibung:
Beim ersten start der App (nachdem man Sie installiert hat) erscheint ein Tutorial.
Durch das Tutorial kann durch geswippt werden, wobei man am Ende auf den Home Bildschirm gelangt.
+ Skip Button zum Überspringen

Weiterhin ist ein Aufruf unter Einstellungen möglich.

Anmerkung:
- App bitte vorher deinstallieren
- Bilder bitte vom Inhalt her bewerten
- Die Auflösung der Bilder ist ldr. derzeit nicht anders möglich (da Bug "outofmemory" bei zu großen Bildern)

2017-06-11 08:42 UTC, joeymez requested changes
Hier zu meiner Review:

Funktionell:
-------------
Die Funktionen der Tutorial-Activity erfüllen den Anforderungen und funktionieren einwandfrei! Das Tutorial erscheint beim ersten Start, lässt sich "skippe"n und ist über den Einstellungen abrufbar!

Design:
---------
Das Design scheint "dahin geschissen"  zu sein (entschuldigt diesen Wortgebrauch). Eine einfache ImageView mit einem Button ohne jegliche Anpassung an unserem gesamten App-Design. Meiner Meinung nach ist dies kein Material-Design und muss auf jeden Fall überarbeitet werden! 

Tipps: 
- Der Hintergrund könnte in Weiß gestalten werden
- Die ImageView sollte nicht über die gesamte Breite / Höhe gehen!
- Der Titel des jeweiligen Tabs ("Tipps: 1 , ... ") würde ich durch Tab-Punkte ersetzten, so wie man es von anderen Apps auch kennt
- Der Skip-Button sollte meiner Meinung nach die selbe Farbe haben wie der Hintergrund (d.h. Weiß), sodass man nur die Schrift sieht und auf diese dann "Skipped"
- Im Allgemeinen würde ich mich am Design eines Dialog-Fensters orientieren :)

Sonstiges:
-----------
Nur kleinere Syntaktische Änderungen die vorgenommen werden müssten :)


Zusammenfassung:
---------------------

Funktionell -> sehr gute Arbeit!
Design-Technisch -> Mangelhaft!

2017-06-11 08:42 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Adapter_Tutorial.java
> +        ctx=c;
Hier bitte immer "this.ctx" verwenden für syntaktischer korrektheit ;)

2017-06-11 08:42 UTC, joeymez commented on app/src/main/java/de/projektss17/bonpix/daten/C_Adapter_Tutorial.java
> +    public void destroyItem(ViewGroup container, int position, Object object) {
Ich habe mal diese Funktion bei mir gelöscht und probiert ob es auch ohne geht. Tatsächlich ist diese Funktion wichtig, da die App sonst abstürzt (Auch wenn die Funktion keinen Inhalt besitzt). Es wäre gut wenn ihr hier zumindest ein Kommentar hinterlasst, in welchem ihr erklärt was diese Funktion macht bzw. wieso diese wichtig ist! :)

2017-06-11 08:42 UTC, joeymez commented on app/src/main/res/layout/box_tutorial_content.xml
> +<?xml version="1.0" encoding="utf-8"?>
Dieses gesamte Layout könnte man theoretisch in die "box_tutorial_screen" reinpacken um unnötige XML-Files zu verhindern. Wurde vermutlich von Android automatisch gemacht beim erstellen der Activity. Ist nicht unbedingt falsch, erzeugt jedoch für mich nur unnötig Garbage (Müssen wir bei den anderen Layouts auch mal schauen und gegebenfalls entfernen) ^^

2017-06-11 08:42 UTC, joeymez commented on app/src/main/res/layout/box_tutorial_screen.xml
> +    <include layout="@layout/box_tutorial_content"
Hier kommt dann beispielsweise anstatt INCLUDE der Inhalt des Layouts box_tutorial_content rein :)

2017-06-12 07:08 UTC, schmitzdominic requested changes
Hi Leute,
finde es sehr gut. Funktionell passt alles und die Anforderungen wurden erfüllt, allerdings ist mir unklar wieso ihr nicht die Texte unter den Bilder mit Inhalt befüllt habt? Ihr wisst das nach diesem Sprint die App auf die Geräte all unserer Testkandidaten installiert wird? Bitte überlegt euch Texte (Falls euch gar nichts einfällt, könnt ihr auch gerne mit mir sprechen), tragt diese in die strings.xml ein und implementiert diese korrekt. Danach gibts von mir auch ein APPROVE ;)

Trotz dessen müsste es noch einmal im nächsten Sprint ein wenig überarbeitet werden.
- Bilder und Tipps müssen ein wenig "professioneller" gestaltet werden. Vielleicht ein wenig in diese Richtung:  https://www.smashingmagazine.com/wp-content/uploads/2014/04/5-Figure-Mailbox-large-opt.png

nur ein Ansatz, ansonsten einen schönen Tag leute :)

2017-06-12 07:08 UTC, schmitzdominic commented on app/build.gradle
> +
Wieso hier drei Absätze? :D

2017-06-12 07:08 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/daten/C_Adapter_Tutorial.java
> +    public void destroyItem(ViewGroup container, int position, Object object) {
Hi Johanns,
das ist nett gemeint von dir aber eigl. unnötig. Es handelt sich hierbei um eine @Override Funktion die normalerweiße schon über die Android API dokumentiert sein dürfte. Siehe [Link zur Google Doku](https://developer.android.com/reference/android/support/v4/view/PagerAdapter.html#destroyItem(android.view.ViewGroup, int, java.lang.Object)).

2017-06-12 07:08 UTC, schmitzdominic commented on app/src/main/res/layout/box_tutorial_adapter.xml
> +                android:text="Tutorial"
Bitte noch mit "title_tutorial" aus der strings.xml verknüpfen. Danke :)

2017-06-12 13:25 UTC, joeymez approved these changes
Bin nochmal durchgegangen und habe persönlich Änderungen durch genommen. Von mir daher ein Approve :)

2017-06-12 13:46 UTC, schmitzdominic approved these changes

2017-06-12 13:46 UTC, merged