i_bug_bounty_daten
schmitzdominic/ProjektSS17 pull request #297
Opened 2017-06-16 18:33 UTC by Xantey

_Beschreibung des Items:_ 
_Das Paket "Daten" soll überprüft werden.
Bitte die Datei [Fragen](https://docs.google.com/document/d/1ElNLLSihZfvd4JII-Iah1te2WZXN_LWqNLuJGfN7Y-s/edit) beachten!_

**PR-Beschreibung:**
Leerzeilen, unnötige Imports, Leerzeichen etc. wurden entfernt. Alle Adapter wurden in ein extra Package ausgelagert.

Die App wurde immer wieder getestet, jedoch kann es sein, dass ich etwas nicht beachtet habe und mir beim löschen ein Fehler unterlaufen ist. **Bitte alles (Code & App) sorgfältig prüfen!**

2017-06-18 22:00 UTC, dontcallme requested changes
Hi Marcus, sieht alles wirklich sehr gut uas, top arbeit!, auch schön mit dem anpassen des Codes, top, funktioniert auch alles noch soweit ich getestet habe.

Nur ein paar kleine Anmerkungen hab ich im Code hinerlassen, schaus dir mal an.

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Favoriten.java
> +
Gut gemacht sieht so besser aus und funktioniert whs auch besser, konnte zumindest keine fehler feststellen :)

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Garantie.java
> +     */
Ist es nötig den Konstruktor immer konkret zu Kennzeichnen?

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Garantie.java
> +        holder.warrantyPrice.setText(bon.getTotalPrice() + " €");   // TODO: € is hardcoded. Has to be implement as Value String in strings.xml or another solution
Am besten gleich mit anlegen, sonst bleibts so^^, dann kann der hässliche Comment raus.

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Laeden.java
> +        if(holder.supShops.contains(shop.getName())){           // Bei Supported Shops darf der Editierbutton nicht erscheinen => Wird unsichtbar gemacht
Ist der Kommentar so richtig eingebunden?, sry da weiß ich jetzt gerade nicht wie wir das machen wollten.

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Laeden.java
> +            public void onClick(View v) {                       // Passing the ShopName to F_Laeden_Detail
Gleiches hier, Kommentar so richtig?

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Statistik.java
>       * Klasse zur Vorbereitung der ArrayLists für die spätere Verarbeitung in den Statistiken
Ist es richtig das das Kommentar am Ende der Methode endet. Handelt es sich huer um eine Klasse?

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/daten/C_Laden.java
leerzeile noch raus.

2017-06-18 22:00 UTC, dontcallme commented on app/src/main/java/de/projektss17/bonpix/recognition/C_MatchLaden.java
leerzeile raus.

2017-06-19 18:12 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/daten/C_Laden.java
hier das gleiche wie unten.

2017-06-19 18:12 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/recognition/C_MatchLaden.java
Hab in die Datei reingeschaut, ich weiß nicht was du meinst. Meines Erachtens ist dort keine Leerzeile mehr, die raus muss 😄

2017-06-19 18:12 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/adapter/C_Adapter_Garantie.java
> +        holder.warrantyPrice.setText(bon.getTotalPrice() + " €");   // TODO: € is hardcoded. Has to be implement as Value String in strings.xml or another solution
Erledigt

2017-06-19 18:49 UTC, schmitzdominic requested changes
Abgelehnt :D

2017-06-19 18:49 UTC, schmitzdominic commented on app/src/main/res/values/strings.xml
> +    <string name="eurozeichen">€</string>
Das exisitert schon :D

2017-06-19 18:53 UTC, merged