I_bug_bounty_allgemein
schmitzdominic/ProjektSS17 pull request #298
Opened 2017-06-17 12:03 UTC by UliVe07

Alle A_Klassen sind angepasst worden mit einheitlichem Leerzeichenlayout + String Aufrufe hinzugefügt bei denen noch Hardgecodet wurde
Tests wurden nach jeder Änderung durchgeführt

2017-06-18 11:10 UTC, schmitzdominic requested changes
Hi ihr zwei,

Wo soll ich Anfangen..
- 1. Bitte NUR über Funktionen die NICHT @Override sind /** */ Kommentare verwenden.
- 2. Bitte entfernt nicht alle @param oder @return Kommentare, diese sind wichtig für den Compiler und helfen anderen Entwicklern unseren Code zu verstehen
- 3. In der Klasse A_Gruppen habt ihr vergessen die Funktion prepareGruppenData zu dokumentieren und generell ist wieder in der Klasse die Frage this. vs nicht this.. bitte entscheidet euch für eine Seite
- 4. Wieso Produziert ihr unnötig viele Leerzeilen? Bitte prüft das nochmal nach

Bitte überarbeitet das alles noch einmal dann gibts von mir auch ein Approve.

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Bon_Anzeigen.java
Wieso sind hier 3 Absätze? :D Glaube einer reicht in diesem Fall ;)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +        /** SWIPPER - Implementierung des Swipper-Funktion */
Bitte dieses Kommentar komplett entfernen. 
Merkt euch bitte das /** Kommentare */ nur über Funktionen stehen. Danke ;)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +
Wieder 3 Zeilen xD

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
>          this.fab = (FloatingActionButton) findViewById(R.id.budget_fab);    //Floating Action Button
wieso ist vor dem this.fab immer noch eine Leerzeile? Ihr instanziiert ja hier allerlei Elemente oder? Das könntet ihr auch alles in einen Block machen. Bitte vergesst nicht, wenn dann alles mit this. oder gar nichts. Danke ;)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
>      public void onStartProofAndCreate() {
Bitte alle Funktionen einer Klasse die nicht @Override sind kommentieren mit /** */. Danke :)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +                /** CARD VIEW - Items können bewegt werden (oben nach unten und umgekehrt) */
Hier schon wieder. Bitte Kommentare innerhalb einer Funktion mit // nicht mit /** */!
Dazu kann dieses Kommentar entfernt werden. Wenn dann Zeilenkommentare. Danke :)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +                /** CARD VIEW - Items werden gelöscht (nach Rechts oder Links) */
Hier schon wieder. Bitte Kommentare innerhalb einer Funktion mit // nicht mit /** */!
Dazu kann dieses Kommentar entfernt werden. Wenn dann Zeilenkommentare. Danke :)

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
>  public class A_Budget_Edit extends AppCompatActivity implements View.OnClickListener{
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> +        /** Implementierung der Objekte in dieser Activity */
Wieder die Kommentare

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> +        /** Setzen des Befehls zum klicken der Edit Text */
Wieder die Kommentare

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
>          saveButton.setOnClickListener(this);
Hier ist wieder die Frage? Überall macht ihr this. davor und genau in diesen 3 Zeilen nicht? wieso?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> +        /** Je nachdem welche EditText angeklickt wird,so wird die Methode createDatePicker ausgeführt */
Wieder so ein Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Einstellungen.java
>  public class A_Einstellungen extends PreferenceActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Einstellungen.java
> +        /** ShakeDetector initialization */
Wieder ein Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Favoriten.java
>  public class A_Favoriten extends AppCompatActivity {
Wieder 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Favoriten.java
>  import android.support.v7.widget.RecyclerView;
In der onResume stellt sich wieder die Frage, this. oder nicht?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Garantie.java
>  public class A_Garantie extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Garantie.java
>  import android.app.SearchManager;
In der onResume stellt sich wieder die Frage, this. oder nicht?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Impressum.java
>  public class A_Impressum extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Laeden.java
>  public class A_Laeden extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Laeden.java
> +        /**Damit der Floating Button beim Scrollen verschwindet */
Wieder ein falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Laeden.java
> +                /** DIALOG Fenster */
Wieder ein falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Laeden.java
> +                                        /**Hinzufügen Laden zur Datenbank */
Wieder ein falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>  public class A_Main extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +    /** Primitive Datentypen */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +    /** Layout */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +    /** Statischer Bereich */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +        /** Navigation Drawer */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +        /** Layout */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +        /** Berechtigungen */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +        /** Instanziierungen und Konfigurationen */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +        /** Wenn ein Menüitem (NavigationDrawer) geklickt wird */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -                        return true;*/
Wieso wurde das entfernt? Hatte gedacht wenn später die Gruppen wieder implementiert werden ist es einfacher das kommi zu entfernen xD

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @return Time Leiste
Wieso wurde das entfernt?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @return boolean
Wieso?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @return FloatingActionButton
Wieso?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
>       */
Hier wieder, wieso entfernt ihr die @param und @return? Das sind wichtige Informationen in der Dokumentation einer Funktion...

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @return true wenn die Activity aufgerufen wurde
Hier schon wieder

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +
Warum wurden hier unnötige Leerzeilen eingefügt?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -         * @return Fragment Instanz
Hier wieder...

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @param grantResults
Hier wieder...

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @param data
Hier wieder...

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +            /** Zurücksetzen um zu gewährleisten das es nicht mehr ausgeführt wird. */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @param value Wie viele Daten generiert werden
Hier wieder...

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Max_Bon_Pic.java
>  public class A_Max_Bon_Pic extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
>  public class A_OCR_Manuell extends AppCompatActivity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Save Button onClickListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
>           * Is setting GuaranteeEnd with FormattedDate and Guarantee Boolean
Bitte auch dieses Kommentar entfernen oder richtig machen.

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                        /** Aufruf der Static-Methode popUpDialog(), welches ein Hinweis-Fenster öffnet */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** OCR Image onClickListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** kamera Button onClickListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Sonstiges Eingabe onClickListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** laden Spinner onClickListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                if ((int) id == 1) { // Itemid == 1 = Benutzerdefiniert, d.h. Wenn manuell eine Marke eingegeben werden soll
Gut gemacht das Kommentar hinter die Zeile zu schreiben, nur leider wurde hier wieder eine Leerzeile zu viel Produziert? wieso?

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            /** Wenn nichts selektiert wurde */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param view standard
Bitte die Parameter drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param v Standard
Bitte die Parameter drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param day Der ausgewählte Tag
Bitte die Parameter drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param v Standard
Bitte die Parameter drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return Zahl mit ggf 0 vorne
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param data Bild daten
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Wenn der Preis nicht leer ist dann setze ihn */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Wenn der Name nicht leer ist dann setze ihn */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Artikel Text changeListener*/
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            /** Wenn der Text geändert wird */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                if (s.toString().isEmpty()) { // Wenn der Text leer ist
Gut gemacht und hinter die Zeile geschrieben :) allerdings schon wieder eine Leerzeile mehr produziert... bitte entfernen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                } else { // Wenn etwas eingegeben wurde
Hier auch die Leerzeile entfernen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Preis Text changeListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            /** Wenn der Text geändert wird */
Falsches Kommentar, kann ganz entfernt werden da die Funktion @Override ist

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                if (s.toString().isEmpty()) { // Wenn der Text leer ist
Wieder eine Leerzeile Produziert

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                } else { // Wenn etwas eingegeben wurde
Wieder eine Leerzeile Produziert

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Preis Text changeListener */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +            /** Wenn der Text geändert wird */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                if (s.toString().isEmpty()) { // Wenn der Text leer ist
Wieder eine Leerzeile Produziert

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                } else { // Wenn etwas eingegeben wurde
Wieder eine Leerzeile Produziert

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return String Array mit allen Preisen
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return Alle Preise summiert als double
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param articles Array mit Articles
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param path Pfad
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return true, alles wurde befüllt. false ein wert fehlt
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Prüft ob ein Laden ausgewählt wurde */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +        /** Prüft ob noch kein Artikel angegeben wurde */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return Uri des Bitmap
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return Status der Maske
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param state Status der Maske
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return ArrayList mit allen Artikeln aus der Maske
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return true - Value Changed, false - Value not Changed
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @return Bon mit allen werten aus der Maske
Bitte die Parameter und Returns drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -        Log.e("BON", saveBon.toString());
Bitte drinnen lassen. Dieser Log ist dafür da um zu wissen was für ein Bon gerade erstellt wird wenn man auf Save drückt.

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab1Home.java
>  public class A_Tab1Home extends Fragment {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab2Statistik.java
>  public class A_Tab2Statistik extends Fragment{
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab2Statistik.java
> +        /** Click eines Tabs bewirkt eine Aktion (in diesem Fall sollen die Charts gefiltert werden) */
Falsches Kommentar

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab2Statistik.java
> +            public void onTabUnselected(TabLayout.Tab tab) {}// MÜSSEN LEIDER mit implementiert werden, machen jedoch nichts!
Wenn ihr so eine Zeile Kommentiert, dann bitte ein Leerzeichen wischen } // danke

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab2Statistik.java
> +            public void onTabReselected(TabLayout.Tab tab) {}// MÜSSEN LEIDER mit implementiert werden, machen jedoch nichts!
Wenn ihr so eine Zeile Kommentiert, dann bitte ein Leerzeichen wischen } // danke

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab2Statistik.java
> -     * @param position Position
Bitte Parameter und Return drinnen lassen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tab3Bons.java
>  public class A_Tab3Bons extends Fragment{
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tutorial.java
>  public class A_Tutorial extends Activity {
Wieder die 3 Zeilen

2017-06-18 11:10 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Tutorial.java
>          btn =(Button) findViewById(R.id.tutorial_skip_button);
Hier wieder this. vs nicht this?

2017-06-18 11:16 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +
Also wir beide haben uns darauf geeinigt, dass es schöner aussieht, wenn es drei Leerzeichen sind als nur eine weil es bei den funktionen schon immer eine ist.

2017-06-18 11:19 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +                /** CARD VIEW - Items können bewegt werden (oben nach unten und umgekehrt) */
Weißt gestern hat jemand gesagt dass wir die alle mit /* machen sollen und wenn die über was drüber stehen nicht //. Dann haben wir des alles geändert und jetzt wieder zurück ändern ist schon kacke :D

2017-06-18 11:20 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
>          saveButton.setOnClickListener(this);
Wir haben an dem Code eigentlich nie was geändert sondern haben den immer so gelassen wie der war als war das der Fehler des Coders. Wir haben hauptsächlich Layout technisch geschaut.

2017-06-18 11:22 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -                        return true;*/
Wir haben gedacht, dass die Gruppen komplett raus sind.

2017-06-18 11:22 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> -     * @return Time Leiste
Weil wir gedacht haben, dass die Beschreibung reicht und die Parameter nur verwirrend sind

2017-06-18 11:24 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> +                if ((int) id == 1) { // Itemid == 1 = Benutzerdefiniert, d.h. Wenn manuell eine Marke eingegeben werden soll
Die haben wir vergessen raus zu nehmen nachdem wir se in die andere zeile gezogen haben -> wird geändert

2017-06-18 11:26 UTC, UliVe07 commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -        Log.e("BON", saveBon.toString());
Gut wird wieder eingefügt

2017-06-18 15:28 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> +                /** CARD VIEW - Items können bewegt werden (oben nach unten und umgekehrt) */
Ja, ich habe gesagt, dass "//" nur hinter Zeilen kommt und oben drüber nur /* benutzt wird. Damit meinte ich aber nicht, dass /* zb innerhalb von Methoden benutzt werden soll.

2017-06-18 15:31 UTC, Xantey commented on app/src/main/java/de/projektss17/bonpix/A_Tutorial.java
>          btn =(Button) findViewById(R.id.tutorial_skip_button);
Leerzeichen nach dem = 😄

2017-06-19 12:55 UTC, schmitzdominic requested changes
Hab immer noch ein paar Sachen gefunden :D

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> -     * @param newPos Neue Postition der View wird übergeben
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> -     * @param position Position der jeweiligen View wird übergeben
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget.java
> -     * @param budget Ein Budget Objekt das hinzugefügt werden soll
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> -     * @param content Übergabe einer Edit Text View
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> -     * @return Rückgabe der Zahl - je nachdem ob transformiert oder  nicht
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Budget_Edit.java
> -     * @return Rückgabe des Boolean-Wertes
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Favoriten.java
> -     * @return true wenn alles hinzugefügt wurde
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Main.java
> +     * @ return boolean
bitte das Leerzeichen raus, da sonst der Compiler nicht damit klar kommt. Danke :)

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param preis Preis des Artikels WICHTIG Preis muss ein , enthalten!
Hier fehlen noch die Parameter

2017-06-19 12:55 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_OCR_Manuell.java
> -     * @param ladenName Ladenname
wieso sind genau die nicht drinnen?

2017-06-19 18:03 UTC, schmitzdominic approved these changes

2017-06-19 19:01 UTC, joeymez requested changes
An sich ist mir diese Leerzeile wurst.... von mir aus kann es drin bleiben, aber es wird wohl andere stören xD

2017-06-19 19:07 UTC, joeymez approved these changes

2017-06-19 19:10 UTC, merged