i_laden_ausgabe
schmitzdominic/ProjektSS17 pull request #310
Opened 2017-06-20 18:30 UTC by SemperF1

Begrenzung der laeden Eingabe.

2017-06-22 16:08 UTC, Xantey approved these changes

2017-06-22 17:26 UTC, joeymez requested changes
Im OCR-Manuell kann der Laden mit einer unbegrenzten Anzahl eingegeben werden. Hier bitte noch eine Begrenzung rein machen :)

Ich habe dir mal ein Screenshot gemacht und habe gleichzeitig den dazugehörigen Code geschrieben um dir die Arbeit zu erleichtern ;) (Auskommentierter Code)

Übernimm es genau so, dann klappts auch! :D

![image](https://user-images.githubusercontent.com/18269678/27447865-f1ab4f3c-5782-11e7-8ef9-0e6c4e51cb14.png)

2017-06-24 12:44 UTC, joeymez reviewed
Alles klar! Pass soweit! :)

2017-06-24 12:45 UTC, joeymez approved these changes

2017-06-24 12:46 UTC, merged