i_artikel_scroll_bug
schmitzdominic/ProjektSS17 pull request #311
Opened 2017-06-20 20:00 UTC by joeymez

Fertigstellung des Items:
---------------------------

Layout:
- löschen der Header XML und hinzufügen dieser in die Screen als festes Layout
- somit Auslagerung des Headers aus der RecyclerView in die Bon_Anzeigen Klasse

Logik:
- Komplette Umschreibung der RecyclerView
- Nur noch eine View-Logik (Artikel) in der RecyclerView
- Anpassung der neuen Logik an die bereits vorhandenen Logiken
- Implementierung und Befüllung der Inhalte für den Header in der onResume (A_Bon_Anzeigen)

INFO: Es scheint als wäre es dennoch Laggy, trotzt Auslagerung des Headers :/

2017-06-20 20:13 UTC, schmitzdominic requested changes
Hey Johanns,
eine Sache wäre noch cool und für dich bestimmt nur ne Sache von 2 sek. Wäre es noch möglich die Preise mit ,00 anzuzeigen? Würde irgendwie intuitiver aussehen ;)

Wenn noch das Kommi drinnen ist gibts ein APPROVE von mir 👍 

Dankeschön :)

2017-06-20 20:13 UTC, schmitzdominic commented on app/src/main/java/de/projektss17/bonpix/A_Bon_Anzeigen.java
> +    public void fillBonHeader(){
Hi Johanns :)
Kannst du das noch bitte kommentieren? 
Vielen Dank ;)

2017-06-20 20:16 UTC, schmitzdominic commented
Hab noch nen Bug gefunden. 
Wenn der Preis sehr hoch ist, verschwindet das € Zeichen, bitte auch noch lösen, danke ;)
![image](https://user-images.githubusercontent.com/23165135/27353891-104cc49e-5606-11e7-9aac-7a13a6c2724d.png)

2017-06-21 16:45 UTC, schmitzdominic commented
Hi Johanns, leider existiert immer noch ein Bug auch nach dem Fix
Dort fehlt das .00 € :(
siehe:
![image](https://user-images.githubusercontent.com/23165135/27395912-bbddfce6-56b1-11e7-8400-c7fba622db2a.png)

2017-06-21 18:55 UTC, schmitzdominic approved these changes

2017-06-21 21:42 UTC, Sippl approved these changes
Habe es Code angeschaut und Funktionaliät getestet, es passt alles soweit.

Ein kleiner bug beim layout ist mir aufgefallen, denn habe ich aber in die Bug Doku aufgenommen, da er nicht zu diesem scroll bug gehört.

2017-06-22 16:07 UTC, merged